version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:10-browsers
    steps:
      - checkout
      - run:
          name: The First Step
          command: |
            echo 'Hello World!'
            echo 'This is the delivery pipeline'
      - run:
          name: List all code files
          command: |
            ls -al
            echo '-----This is surely my code----'
      - run:
          name: Running in a container with Node installed
          command: |
            node -v
